# Generated by Django 4.2 on 2024-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeryanalytics', '0003_auto_20210314_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskcompleted',
            name='task',
            field=models.CharField(help_text='This is the Full path to the python function module.name. Not the Celery Registered Task name', max_length=500),
        ),
        migrations.AlterField(
            model_name='celerytaskfailed',
            name='task',
            field=models.CharField(help_text='This is the Full path to the python function module.name. Not the Celery Registered Task name', max_length=500),
        ),
    ]
